### PR TITLE
[CI] add Ubuntu image & GCC compiler to appveyor build matrix

### PR DESCRIPTION
**Pull request by MomoDeve**

### CODE REVIEW

**Comment by MomoDeve** [comment]
Damn... Seems like it's no longer working - I somehow have negative credit balance and cannot launch the build

**Comment by MomoDeve** [comment]
Maybe it's better to just switch to appveyour and have it all in one place

**Comment by MomoDeve** [comment]
@fall2019 sorry for stopping you build in the #67 ... I am trying to add GCC/Clang to appveyor CI. Need to add artefacts for them too

**Comment by fall2019** [comment]
> @fall2019 sorry for stopping you build in the #67 ... I am trying to add GCC/Clang to appveyor CI. Need to add artefacts for them too

It's okay. Yeah they also need artifacts. I did read some docs and still working on it.

**Pull request merged**
